"""add earning_rate in level table

Revision ID: 64eb47ae5236
Revises: 7b23ca11d28a
Create Date: 2018-02-07 12:46:12.209595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eb47ae5236'
down_revision = '7b23ca11d28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('earning_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'earning_rate')
    # ### end Alembic commands ###
