"""add user display name field

Revision ID: ea6057506937
Revises: 367c24bbd05c
Create Date: 2018-02-24 23:54:21.429386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6057506937'
down_revision = '367c24bbd05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
